apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-edera-files"
spec:
  kprobes:
    - call: "sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string"
